/**
 * Default Strategy Configuration
 *
 * SOURCE_CONFIG: How much to trust each data source
 * DEFAULT_CONFIG: Base trading parameters
 * DEFAULT_STATE: Initial state for a fresh agent
 */

import { createInitialAgentState } from "../../core/initial-state";
import type { AgentConfig, AgentState } from "../../core/types";

// ── Source weights & tuning ──────────────────────────────────────────────────

export const SOURCE_CONFIG = {
  weights: {
    stocktwits: 0.85,
    reddit_wallstreetbets: 0.45,
    reddit_stocks: 0.9,
    reddit_investing: 0.8,
    reddit_options: 0.85,
    twitter_fintwit: 0.85,
    twitter_news: 0.9,
    alpha_vantage_news: 0.88,
    gdelt_news: 0.72,
    sec_8k: 0.95,
    sec_4: 0.9,
    sec_13f: 0.7,
    sec_major_filing: 0.82,
  },
  flairMultipliers: {
    DD: 1.5,
    "Technical Analysis": 1.3,
    Fundamentals: 1.3,
    News: 1.2,
    Discussion: 1.0,
    Chart: 1.1,
    "Daily Discussion": 0.7,
    "Weekend Discussion": 0.6,
    YOLO: 0.6,
    Gain: 0.5,
    Loss: 0.5,
    Meme: 0.4,
    Shitpost: 0.3,
  } as Record<string, number>,
  engagement: {
    upvotes: { 1000: 1.5, 500: 1.3, 200: 1.2, 100: 1.1, 50: 1.0, 0: 0.8 } as Record<number, number>,
    comments: { 200: 1.4, 100: 1.25, 50: 1.15, 20: 1.05, 0: 0.9 } as Record<number, number>,
  },
  decayHalfLifeMinutes: 120,
};

// ── Default agent configuration ──────────────────────────────────────────────

export const DEFAULT_CONFIG: AgentConfig = {
  data_poll_interval_ms: 30_000,
  analyst_interval_ms: 120_000,
  premarket_plan_window_minutes: 5,
  market_open_execute_window_minutes: 2,
  max_position_value: 5000,
  max_positions: 5,
  min_sentiment_score: 0.3,
  min_analyst_confidence: 0.6,
  signal_research_limit: 5,
  max_entry_research_age_minutes: 30,
  entry_candidate_limit: 3,
  min_entry_selection_score: 0.85,
  min_entry_quality: "good",
  max_entry_red_flags: 0,
  min_entry_catalysts: 1,
  min_entry_signal_sources: 1,
  min_entry_signal_consensus: 0.15,
  single_source_entry_min_confidence: 0.82,
  exceptional_entry_confidence: 0.9,
  analyst_buy_requires_research_confirmation: true,
  llm_size_conviction_scaling: true,
  llm_size_low_confidence_multiplier: 0.4,
  llm_size_medium_confidence_multiplier: 0.7,
  equity_entry_cooldown_minutes_after_open: 10,
  equity_entry_cutoff_minutes_before_close: 15,
  max_entry_spread_pct: 0.8,
  min_entry_quote_size: 1,
  max_entry_price_change_pct: 5,
  bad_fill_exit_enabled: true,
  bad_fill_max_slippage_pct: 0.5,
  bad_fill_loss_pct: 0.5,
  bad_fill_max_hold_minutes: 30,
  early_loss_exit_enabled: true,
  early_loss_exit_pct: 2.5,
  early_loss_exit_max_hold_minutes: 90,
  after_hours_exit_limit_buffer_pct: 0.25,
  entry_timing_enabled: true,
  entry_rsi_min: 40,
  entry_rsi_max: 55,
  entry_bb_lower_threshold: 0.2,
  entry_max_intraday_range_position: 0.75,
  market_regime_enabled: true,
  regime_low_threshold: 0.5,
  regime_position_size_reduction: 0.45,
  portfolio_risk_enabled: true,
  max_positions_per_sector: 2,
  max_daily_loss_pct: 0.02,
  daily_loss_entry_guard_enabled: true,
  daily_loss_entry_guard_pct: 0.0075,
  daily_loss_guard_min_confidence: 0.8,
  daily_loss_guard_min_entry_quality: "good",
  open_position_loss_entry_guard_enabled: true,
  open_position_loss_entry_guard_pct: 0.01,
  open_position_loss_guard_min_confidence: 0.85,
  open_position_loss_guard_min_entry_quality: "excellent",
  cooldown_minutes_after_loss: 30,
  max_daily_entry_orders: 8,
  min_minutes_between_entries: 5,
  adaptive_performance_block_enabled: true,
  adaptive_performance_lookback_days: 90,
  adaptive_performance_min_trades: 3,
  adaptive_performance_min_win_rate: 0.35,
  llm_force_sell_pnl_pct: 2,
  llm_force_sell_min_confidence: 0.65,
  take_profit_pct: 10,
  stop_loss_pct: 5,
  trailing_stop_enabled: true,
  trailing_stop_activation_pct: 6,
  trailing_stop_drawdown_pct: 3,
  breakeven_stop_enabled: true,
  breakeven_stop_activation_pct: 4,
  breakeven_stop_buffer_pct: 0.25,
  profit_lock_stop_enabled: true,
  profit_lock_activation_pct: 3,
  profit_lock_floor_pct: 0.5,
  sentiment_reversal_exit_enabled: true,
  sentiment_reversal_min_hold_minutes: 60,
  sentiment_reversal_loss_pct: 1.5,
  sentiment_reversal_threshold: -0.25,
  sentiment_reversal_min_sources: 1,
  position_size_pct_of_cash: 25,
  stale_position_enabled: true,
  stale_min_hold_hours: 24,
  stale_loss_exit_pct: 2,
  stale_max_hold_days: 3,
  stale_min_gain_pct: 5,
  stale_mid_hold_days: 1,
  stale_mid_min_gain_pct: 3,
  stale_social_volume_decay: 0.3,
  llm_provider: "openai-raw",
  llm_model: "gpt-4o-mini",
  llm_analyst_model: "gpt-4o",
  openai_base_url: "",
  llm_min_hold_minutes: 30,
  recent_sell_cooldown_hours: 72,
  defensive_sell_cooldown_hours: 168,
  options_enabled: false,
  options_min_confidence: 0.8,
  options_max_pct_per_trade: 0.02,
  options_min_dte: 30,
  options_max_dte: 60,
  options_target_delta: 0.45,
  options_min_delta: 0.3,
  options_max_delta: 0.7,
  options_max_spread_pct: 8,
  options_early_loss_exit_enabled: true,
  options_early_loss_exit_pct: 25,
  options_early_loss_exit_max_hold_minutes: 60,
  options_stop_loss_pct: 50,
  options_take_profit_pct: 100,
  crypto_enabled: false,
  crypto_symbols: ["BTC/USD", "ETH/USD", "SOL/USD"],
  crypto_max_positions: 3,
  crypto_momentum_threshold: 2.0,
  crypto_max_momentum_pct: 12,
  crypto_max_position_value: 1000,
  crypto_take_profit_pct: 10,
  crypto_stop_loss_pct: 5,
  ticker_blacklist: [],
  allowed_exchanges: ["NYSE", "NASDAQ", "ARCA", "AMEX", "BATS"],
  starting_equity: 100_000,
  twitter_cookies: "",
  twitter_cookie_accounts: [],
  reddit_cookies: "",
  reddit_cookie_accounts: [],
  reddit_user_agent:
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
  alpha_vantage_api_key: "",
  discord_webhook_url: "",
  discord_daily_report_enabled: false,
  discord_daily_report_time: "21:00",
  discord_daily_report_timezone: "Asia/Tokyo",
};

// ── Default agent state ──────────────────────────────────────────────────────

export const DEFAULT_STATE: AgentState = {
  config: DEFAULT_CONFIG,
  signalCache: [],
  positionEntries: {},
  recentSells: {},
  missedEntryOpportunities: {},
  socialHistory: {},
  socialSnapshotCache: {},
  socialSnapshotCacheUpdatedAt: 0,
  logs: [],
  costTracker: { total_usd: 0, calls: 0, tokens_in: 0, tokens_out: 0 },
  lastDataGatherRun: 0,
  lastAlarmStartedAt: 0,
  lastAnalystRun: 0,
  lastResearchRun: 0,
  lastPositionResearchRun: 0,
  signalResearch: {},
  positionResearch: {},
  stalenessAnalysis: {},
  twitterConfirmations: {},
  twitterDailyReads: 0,
  twitterDailyReadReset: 0,
  lastKnownNextOpenMs: null,
  premarketPlan: null,
  lastPremarketPlanDayEt: null,
  lastClockIsOpen: null,
  lastDiscordDailyReportDay: null,
  enabled: false,
};
